# SPDX-FileCopyrightText: Silex Data Solutions
# SPDX-License-Identifier: Apache-2.0
"""The contract between the shared CI and the collections it writes into.

Every file a reusable workflow commits to a collection - the skeleton sync's
managed files (.claude/ and the shared tooling configuration) and changelog
fragment, the release's version bump and changelog - must pass that
collection's own CI. The step tests next door check
each step's logic against fixtures, which encode our assumptions; this checks
the real output against the real rules, by generating a collection from the
skeleton, running the steps against it, and running the collection's own Lint
(pre-commit) and Nox (every default session) on a fresh clone of the result.

It runs from both sides, so a change to either is tested against the other:

- Selftest, on PRs into `ci`: these steps against the skeleton on `main`.
- Selfcheck, on PRs into `main`: the steps at `v1` against that PR's skeleton.

CONTRACT_SKELETON_DIR points at a silexdata.collection_skeleton checkout.
Without it, as in the plain step-test job, these tests are skipped. They need
ansible-core, antsibull-changelog, pre-commit, nox and antsibull-nox.
"""

import json
import os
import pathlib
import shutil
import subprocess

import pytest

# Resolved now: the steps run with other working directories.
SKELETON = os.environ.get("CONTRACT_SKELETON_DIR") and os.path.abspath(
    os.environ["CONTRACT_SKELETON_DIR"]
)
pytestmark = pytest.mark.skipif(not SKELETON, reason="CONTRACT_SKELETON_DIR is not set")

VARS = {
    "namespace": "silexdata",
    "collection_name": "contract",
    "description": "Generated by the ci branch's contract test.",
    "authors": ["Silex Data Solutions <info@silexdata.com>"],
    "repository": "https://github.com/SilexDataTeam/silexdata.contract",
    "issues": "https://github.com/SilexDataTeam/silexdata.contract/issues",
    "homepage": "https://www.silexdata.com/",
    "documentation": "https://galaxy.ansible.com/ui/repo/published/silexdata/contract/docs/",
}
SYNC_BRANCH = "sync/skeleton"


def run(cwd, *args, check=True):
    proc = subprocess.run(
        list(args),
        cwd=cwd,
        capture_output=True,
        text=True,
        stdin=subprocess.DEVNULL,
        check=False,
    )
    if check and proc.returncode != 0:
        raise AssertionError(
            f"{' '.join(args)} failed in {cwd} (rc={proc.returncode}):\n"
            f"{proc.stdout[-4000:]}\n{proc.stderr[-4000:]}"
        )
    return proc


def git(cwd, *args):
    return run(
        cwd,
        "git",
        "-c",
        "user.name=contract",
        "-c",
        "user.email=contract@localhost",
        *args,
    ).stdout


@pytest.fixture(scope="session")
def nox_envdir(tmp_path_factory):
    """One set of nox virtualenvs for every collection checked here."""
    return tmp_path_factory.mktemp("nox-envs")


@pytest.fixture
def collection(tmp_path):
    """A clone of a freshly generated collection, whose origin/main holds it."""
    vars_file = tmp_path / "vars.json"
    vars_file.write_text(json.dumps(VARS))
    run(
        tmp_path,
        "ansible-galaxy",
        "collection",
        "init",
        "silexdata.contract",
        "--collection-skeleton",
        str(pathlib.Path(SKELETON, "skeleton")),
        "--init-path",
        str(tmp_path / "gen"),
        "-e",
        f"@{vars_file}",
    )
    origin, clone = tmp_path / "origin.git", tmp_path / "clone"
    git(tmp_path, "init", "--quiet", "--bare", "--initial-branch=main", str(origin))
    shutil.copytree(tmp_path / "gen" / "silexdata" / "contract", clone)
    git(clone, "init", "--quiet", "--initial-branch=main")
    git(clone, "remote", "add", "origin", str(origin))
    git(clone, "add", "-A")
    git(clone, "commit", "--quiet", "-m", "chore(init): generate the collection")
    git(clone, "push", "--quiet", "origin", "main")
    return clone


def collection_ci(tmp_path, origin, ref, nox_envdir):
    """Run the collection's own Lint and Nox on a fresh clone of `ref`, as its PR would."""
    checkout = tmp_path / f"ci-{ref.replace('/', '-')}"
    git(tmp_path, "clone", "--quiet", "--branch", ref, str(origin), str(checkout))
    lint = run(
        checkout,
        "pre-commit",
        "run",
        "--all-files",
        "--show-diff-on-failure",
        check=False,
    )
    nox = run(
        checkout,
        "nox",
        "--envdir",
        str(nox_envdir),
        "--reuse-existing-virtualenvs",
        check=False,
    )
    failures = []
    if lint.returncode:
        failures.append("Lint (pre-commit) failed:\n" + lint.stdout[-4000:])
    if nox.returncode:
        failures.append(
            "Nox (default sessions) failed:\n" + (nox.stdout + nox.stderr)[-4000:]
        )
    assert not failures, f"{ref} would fail the collection's CI:\n\n" + "\n\n".join(
        failures
    )


def test_a_fresh_collection_passes_its_own_ci(tmp_path, collection, nox_envdir):
    """The baseline: otherwise a failure below says nothing about the CI's output."""
    collection_ci(tmp_path, tmp_path / "origin.git", "main", nox_envdir)


def test_the_rules_sync_output_passes_the_collections_ci(
    tmp_path, step, collection, nox_envdir
):
    # Drift on the collection's main, in both kinds of managed path - a
    # mirrored directory and a copied file - which the sync must undo.
    rule = sorted((collection / ".claude" / "rules").glob("*.md"))[0]
    rule.write_text(rule.read_text() + "\nA local edit the skeleton does not have.\n")
    pyproject = collection / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text() + "\n# A local edit the skeleton does not have.\n"
    )
    git(collection, "commit", "--quiet", "-am", "chore: drift from the skeleton")
    git(collection, "push", "--quiet", "origin", "main")

    # What the workflow's sparse checkout of the skeleton holds.
    src = collection / ".skeleton-src"
    shutil.copytree(pathlib.Path(SKELETON, "skeleton"), src / "skeleton")
    shutil.copy(pathlib.Path(SKELETON, "sync-manifest.txt"), src / "sync-manifest.txt")
    mirror = step(
        "reusable-sync-rules.yml",
        "sync",
        "mirror",
        {
            "SRC_ROOT": ".skeleton-src/skeleton",
            "MANIFEST": ".skeleton-src/sync-manifest.txt",
        },
        cwd=collection,
    )
    assert mirror.returncode == 0, mirror.stdout
    assert mirror.outputs["changed"] == "true"
    commit = step(
        "reusable-sync-rules.yml",
        "sync",
        "commit",
        {
            "BRANCH": SYNC_BRANCH,
            "FRAGMENT": "changelogs/fragments/sync-skeleton.yml",
            "MANIFEST": ".skeleton-src/sync-manifest.txt",
        },
        cwd=collection,
    )
    assert commit.returncode == 0, commit.stdout
    assert commit.outputs["pushed"] == "true"

    collection_ci(tmp_path, tmp_path / "origin.git", SYNC_BRANCH, nox_envdir)


def test_the_release_output_passes_the_collections_ci(
    tmp_path, step, collection, nox_envdir
):
    # A merged PR carrying the fragment that cuts the first release.
    fragment = collection / "changelogs" / "fragments" / "initial-release.yml"
    fragment.write_text(
        "---\nrelease_summary: Initial release.\nmajor_changes:\n  - Initial release.\n"
    )
    git(collection, "add", "-A")
    git(collection, "commit", "--quiet", "-m", "feat: cut the first release")

    ver = step("reusable-release.yml", "release", "ver", {}, cwd=collection)
    assert ver.returncode == 0, ver.stdout
    assert ver.outputs["version"] == "1.0.0"
    for step_id in ("bump", "changelog"):
        result = step(
            "reusable-release.yml",
            "release",
            step_id,
            {"VERSION": "1.0.0"},
            cwd=collection,
        )
        assert result.returncode == 0, result.stdout
    # What the release's commit step pushes: the same files, on the default branch.
    git(collection, "add", "-A", "galaxy.yml", "CHANGELOG.md", "changelogs/")
    git(collection, "commit", "--quiet", "-m", "chore(release): 1.0.0")
    git(collection, "push", "--quiet", "origin", "main")

    collection_ci(tmp_path, tmp_path / "origin.git", "main", nox_envdir)
